# Generated by Django 3.2.15 on 2022-09-23 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220923_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='pieces',
            new_name='rooms',
        ),
        migrations.AddField(
            model_name='description',
            name='city',
            field=models.CharField(default='Abidjan', max_length=100),
        ),
        migrations.AddField(
            model_name='description',
            name='country',
            field=models.CharField(default="Côte d'Ivoire", max_length=100),
        ),
        migrations.AddField(
            model_name='description',
            name='district',
            field=models.CharField(default='Marcory', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='expire_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tenant',
            name='status_payment',
            field=models.BooleanField(default=False),
        ),
    ]
