# Generated by Django 3.2.15 on 2022-09-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220923_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='surface_m2',
            field=models.IntegerField(default=0),
        ),
    ]
